version: '3.7'

services:
  minicloud_backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: minicloud_backend
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: npm run dev

volumes:
  db: